name: e_invoice
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^13.0.1
  google_fonts: ^6.1.0
  percent_indicator: ^4.2.3
  iconsax: ^0.0.8
  flutter_screenutil: ^5.9.0
  syncfusion_flutter_charts: ^24.1.47+2
  fl_chart: ^0.66.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
